In [1]:
# import
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# inline for testing
%matplotlib inline

In [3]:
# Physician
physician = pd.read_csv('..\data\Physician_&_Other_Supplier_Payments\Medicare_Provider_Util_Payment_PUF_CY2017.txt', 
                           sep = "\t",
                           usecols = ['npi', 'nppes_provider_last_org_name','nppes_provider_first_name', 'nppes_credentials', 'nppes_entity_code', 'place_of_service', 'nppes_provider_zip', 'nppes_provider_state', 'hcpcs_code','bene_day_srvc_cnt', 'average_Medicare_allowed_amt', 'provider_type'],
#                            chunksize = 100000,
                            skiprows =[1],
                           dtype = {
                               'nppes_provider_zip': 'str'
                           })
physician.columns = physician.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

In [4]:
# Hospital 
# create filepaths 
hospital = pd.read_csv('..\data\Hospital_Outpatient\Provider_Outpatient_Hospital_Charge_Data_by_APC__CY2017.csv',
                          usecols=[0,1,3,4,5,7,8,10,12],
                          dtype = {
                              'Provider_Zip_Code': 'str',
                              'APC': 'str'
                          })
# if it breaks, take out col 1
hospital.columns = hospital.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

In [5]:
# ZIP
cbsa = pd.read_csv('..\data\Zip_Code_to_CBSA\ZIP_CBSA_032020.csv',
                  usecols =['ZIP', 'CBSA'],
                  dtype ={
                      'ZIP': 'str',
                      'CBSA': 'str'
                  })

In [6]:
# Crosswalk
crosswalk = pd.read_csv('..\\data\\APC_to_CPTHCPCS_crosswalk\\2020_january_web_addendum_b.12312019.csv', 
                        header=2, 
                        dtype ={
                            'APC': 'str'
                        })
# crosswalk = crosswalk.rename(columns=lambda x: x.strip())
crosswalk.columns = crosswalk.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

In [7]:
#zip to 5 digits
physician['nppes_provider_zip'] = physician['nppes_provider_zip'].str[:5]

Get every zipcode to have a CBSA

In [8]:
physician.head()

npi nppes_provider_last_org_name nppes_provider_first_name  \
0  1003000126                    ENKESHAFI                   ARDALAN   
1  1003000126                    ENKESHAFI                   ARDALAN   
2  1003000126                    ENKESHAFI                   ARDALAN   
3  1003000126                    ENKESHAFI                   ARDALAN   
4  1003000126                    ENKESHAFI                   ARDALAN   

  nppes_credentials nppes_entity_code nppes_provider_zip nppes_provider_state  \
0              M.D.                 I              21502                   MD   
1              M.D.                 I              21502                   MD   
2              M.D.                 I              21502                   MD   
3              M.D.                 I              21502                   MD   
4              M.D.                 I              21502                   MD   

       provider_type place_of_service hcpcs_code  bene_day_srvc_cnt  \
0  Internal Medicine                F      99217                100   
1  Internal Medicine                F      99218                 26   
2  Internal Medicine                F      99219                 52   
3  Internal Medicine                F      99220                 59   
4  Internal Medicine                F      99221                 16   

   average_medicare_allowed_amt  
0                     73.398800  
1                    100.080000  
2                    136.380000  
3                    190.363729  
4                    101.680000

In [9]:
# Assign every zipcode a CBSA
physician_with_cbsa = pd.merge(physician, cbsa, how='left', left_on='nppes_provider_zip', right_on='ZIP')

In [10]:
physician_with_cbsa = physician_with_cbsa.drop('ZIP', axis =1)

In [11]:
# physician_with_cbsa

This is every state

In [12]:
# Assign every hcpcs code an APC
physician_full_merge = pd.merge(physician_with_cbsa, crosswalk[['hcpcs_code', 'apc']], on='hcpcs_code', how='left')

In [13]:
# Get CBSAs for Nashville
cbsa_34980 =cbsa[cbsa['CBSA']== '34980']

# and New York
cbsa_35620 = cbsa[cbsa['CBSA'] == '35620']

# Chicago 16980


In [14]:
# Create variable holding all unique zip codes within CBSA
# Nash
zip_34980 = cbsa_34980['ZIP'].unique()

# New York
zip_35620 = cbsa_35620['ZIP'].unique()

In [15]:
# Seperator
# Seperator
# Seperator
# Seperator
# Seperator
# Seperator

In [16]:
# Narrow down Entity Type to O, Provider to ASC, CPt to 43249
# This is NATION wide
physician_filtered_opt1 = physician_with_cbsa[(physician_with_cbsa['nppes_entity_code'] == 'O') & (physician_with_cbsa['provider_type'] == 'Ambulatory Surgical Center')]

In [17]:
# Let's narrow it down to just Nashville 
# This is ALL Nashville providers and procedures
nash_provider = physician_filtered_opt1[physician_filtered_opt1.nppes_provider_zip.isin(zip_34980)]

In [18]:
# Narrow down to CPT 43249
nash_prov_43249 = nash_provider[nash_provider['hcpcs_code'] == '43249']

In [19]:
nash_prov_43249 = nash_prov_43249.drop(['nppes_entity_code', 'place_of_service', 'nppes_provider_state'], axis=1)

USE THIS TABLE FOR NASHVILLE PROVIDERS

In [20]:
nash_prov_43249

npi           nppes_provider_last_org_name  \
1419489  1124498357  ENDOSCOPY CENTER OF INLAND EMPIRE LLC   
2434815  1225039761       ENDOSCOPY CENTER OF ST THOMAS LP   
3211255  1295708964          COLUMBIA TN ENDOSCOPY ASC LLC   
3211256  1295708964          COLUMBIA TN ENDOSCOPY ASC LLC   
4676285  1427152073                   PATIENT PARTNERS LLC   
6997001  1639299803        MURFREESBORO MEDICAL CLINIC P A   

        nppes_provider_first_name nppes_credentials nppes_provider_zip  \
1419489                       NaN               NaN              37219   
2434815                       NaN               NaN              37205   
3211255                       NaN               NaN              38401   
3211256                       NaN               NaN              38401   
4676285                       NaN               NaN              37066   
6997001                       NaN               NaN              37129   

                      provider_type hcpcs_code  bene_day_srvc_cnt  \
1419489  Ambulatory Surgical Center      43249                 16   
2434815  Ambulatory Surgical Center      43249                 17   
3211255  Ambulatory Surgical Center      43249                 34   
3211256  Ambulatory Surgical Center      43249                 34   
4676285  Ambulatory Surgical Center      43249                 23   
6997001  Ambulatory Surgical Center      43249                 33   

         average_medicare_allowed_amt   CBSA  
1419489                    660.990000  34980  
2434815                    565.636471  34980  
3211255                    587.110000  30280  
3211256                    587.110000  34980  
4676285                    587.110000  34980  
6997001                    587.110000  34980

In [21]:
# Let's narrow it down to just NY 
# This is ALL NY providers and procedures
ny_provider = physician_filtered_opt1[physician_filtered_opt1.nppes_provider_zip.isin(zip_35620)]

In [22]:
# Narrow down to CPT 43249
ny_prov_43249 = ny_provider[ny_provider['hcpcs_code'] == '43249']

In [23]:
ny_prov_43249 = ny_prov_43249.drop(['nppes_entity_code', 'place_of_service', 'nppes_provider_state'], axis=1)

USE THIS TABLE FOR NEW YORK PROVIDERS

In [24]:
ny_prov_43249

npi                 nppes_provider_last_org_name  \
1406803   1124324181               MANHATTAN ENDOSCOPY CENTER LLC   
1580610   1144291261                  OCEAN SURGICAL PAVILION, PC   
1961060   1174873780                     YORKVILLE ENDOSCOPY, LLC   
2264921   1205875283                  RWJ ENDOSURGICAL CENTER LLC   
2323393   1215134564                  EMMAUS SURGICAL CENTER, LLC   
2323394   1215134564                  EMMAUS SURGICAL CENTER, LLC   
2561010   1235178146               SUBURBAN ENDOSCOPY CENTER, LLC   
2626485   1235551052  LONG ISLAND DIGESTIVE ENDOSCOPY CENTER, LLC   
5144601   1467696815            MORRIS COUNTY SURGICAL CENTER LLC   
5211148   1477584621                 HANOVER NJ ENDOSCOPY ASC LLC   
7878035   1710948302              ENDOSCOPY CENTER OF RED BANK PA   
8555663   1770847717          ENDOSCOPY CENTER OF HACKENSACK, LLC   
9709619   1881667368               FLORHAM PARK ENDOSCOPY ASC LLC   
9864830   1891881926            GASTRO-SURGI CENTER OF NEW JERSEY   
10249659  1932164852                 MAY STREET SURGI CENTER, LLC   
10298090  1932321882        DIGESTIVE HEALTH CENTER OF HUNTINGTON   
10670491  1972526242             SURGICARE OF CENTRAL JERSEY, LLC   
10677095  1972541415                 OCEAN ENDOSURGERY CENTER LLC   
10790490  1982641890                     SUMMIT MEDICAL GROUP, PA   

         nppes_provider_first_name nppes_credentials nppes_provider_zip  \
1406803                        NaN               NaN              10017   
1580610                        NaN               NaN              07755   
1961060                        NaN               NaN              10128   
2264921                        NaN               NaN              08816   
2323393                        NaN               NaN              07840   
2323394                        NaN               NaN              07840   
2561010                        NaN               NaN              07044   
2626485                        NaN               NaN              11776   
5144601                        NaN               NaN              07054   
5211148                        NaN               NaN              07981   
7878035                        NaN               NaN              07701   
8555663                        NaN               NaN              07601   
9709619                        NaN               NaN              07932   
9864830                        NaN               NaN              07092   
10249659                       NaN               NaN              08837   
10298090                       NaN               NaN              11743   
10670491                       NaN               NaN              07069   
10677095                       NaN               NaN              08755   
10790490                       NaN               NaN              07922   

                       provider_type hcpcs_code  bene_day_srvc_cnt  \
1406803   Ambulatory Surgical Center      43249                 33   
1580610   Ambulatory Surgical Center      43249                 11   
1961060   Ambulatory Surgical Center      43249                 28   
2264921   Ambulatory Surgical Center      43249                 17   
2323393   Ambulatory Surgical Center      43249                 14   
2323394   Ambulatory Surgical Center      43249                 14   
2561010   Ambulatory Surgical Center      43249                 12   
2626485   Ambulatory Surgical Center      43249                 15   
5144601   Ambulatory Surgical Center      43249                 13   
5211148   Ambulatory Surgical Center      43249                 41   
7878035   Ambulatory Surgical Center      43249                 33   
8555663   Ambulatory Surgical Center      43249                 23   
9709619   Ambulatory Surgical Center      43249                 21   
9864830   Ambulatory Surgical Center      43249                 18   
10249659  Ambulatory Surgical Center      43249                 12   
10298090  Ambul

Get the same result for hospitals

In [25]:
hospital.head()

provider_id                     provider_name provider_city provider_state  \
0        10001  Southeast Alabama Medical Center        Dothan             AL   
1        10001  Southeast Alabama Medical Center        Dothan             AL   
2        10001  Southeast Alabama Medical Center        Dothan             AL   
3        10001  Southeast Alabama Medical Center        Dothan             AL   
4        10001  Southeast Alabama Medical Center        Dothan             AL   

  provider_zip_code   apc                                           apc_desc  \
0             36301  5072    Level 2 Excision/ Biopsy/ Incision and Drainage   
1             36301  5073    Level 3 Excision/ Biopsy/ Incision and Drainage   
2             36301  5091  Level 1 Breast/Lymphatic Surgery and Related P...   
3             36301  5092  Level 2 Breast/Lymphatic Surgery and Related P...   
4             36301  5112                 Level 2 Musculoskeletal Procedures   

   capc_services  average_medicare_allowed_amount  
0            259                          1038.45  
1             53                          1792.60  
2             27                          2113.58  
3             23                          3737.14  
4             17                          1029.46

In [26]:
# Assign every zipcode a CBSA
hospital_with_cbsa = pd.merge(hospital, cbsa, how='left', left_on='provider_zip_code', right_on='ZIP')

This is every state - hospital

In [27]:
hospital_with_cbsa

provider_id                             provider_name  provider_city  \
0            10001          Southeast Alabama Medical Center         Dothan   
1            10001          Southeast Alabama Medical Center         Dothan   
2            10001          Southeast Alabama Medical Center         Dothan   
3            10001          Southeast Alabama Medical Center         Dothan   
4            10001          Southeast Alabama Medical Center         Dothan   
...            ...                                       ...            ...   
71065       670122  Houston Methodist The Woodlands Hospital  The Woodlands   
71066       670122  Houston Methodist The Woodlands Hospital  The Woodlands   
71067       670122  Houston Methodist The Woodlands Hospital  The Woodlands   
71068       670122  Houston Methodist The Woodlands Hospital  The Woodlands   
71069       670122  Houston Methodist The Woodlands Hospital  The Woodlands   

      provider_state provider_zip_code   apc  \
0                 AL             36301  5072   
1                 AL             36301  5073   
2                 AL             36301  5091   
3                 AL             36301  5092   
4                 AL             36301  5112   
...              ...               ...   ...   
71065             TX             77385  5361   
71066             TX             77385  5373   
71067             TX             77385  5375   
71068             TX             77385  5431   
71069             TX             77385  8011   

                                                apc_desc  capc_services  \
0        Level 2 Excision/ Biopsy/ Incision and Drainage            259   
1        Level 3 Excision/ Biopsy/ Incision and Drainage             53   
2      Level 1 Breast/Lymphatic Surgery and Related P...             27   
3      Level 2 Breast/Lymphatic Surgery and Related P...             23   
4                     Level 2 Musculoskeletal Procedures             17   
...                                                  ...            ...   
71065           Level 1 Laparoscopy and Related Services             18   
71066               Level 3 Urology and Related Services             11   
71067               Level 5 Urology and Related Services             21   
71068                           Level 1 Nerve Procedures             12   
71069                 Comprehensive Observation Services            165   

       average_medicare_allowed_amount    ZIP   CBSA  
0                              1038.45  36301  20020  
1                              1792.60  36301  20020  
2                              2113.58  36301  20020  
3                              3737.14  36301  20020  
4                              1029.46  36301  20020  
...                                ...    ...    ...  
71065                          3866.82  77385  26420  
71066                          1469.87  77385  26420  
71067                          3356.89  77385  26420  
71068                          1506.38  77385  26420  
71069                          2141.54  77385  26420  

[71070 rows x 11 columns]

In [28]:
hospital_with_cbsa = hospital_with_cbsa.drop('ZIP', axis =1)

In [29]:
# Filter to just Nashville Hospitals
# This is ALL Nashville providers and procedures
nash_hospital = hospital_with_cbsa[hospital_with_cbsa.provider_zip_code.isin(zip_34980)]

In [30]:
# Filter down to the right apc
nash_hospital

provider_id                      provider_name provider_city  \
57520       440073            Maury Regional Hospital      Columbia   
57521       440073            Maury Regional Hospital      Columbia   
57574       440003     Sumner Regional Medical Center      Gallatin   
57575       440003     Sumner Regional Medical Center      Gallatin   
57576       440003     Sumner Regional Medical Center      Gallatin   
...            ...                                ...           ...   
59312       440227  Tristar Stonecrest Medical Center        Smyrna   
59313       440227  Tristar Stonecrest Medical Center        Smyrna   
59314       440227  Tristar Stonecrest Medical Center        Smyrna   
59315       440227  Tristar Stonecrest Medical Center        Smyrna   
59316       440227  Tristar Stonecrest Medical Center        Smyrna   

      provider_state provider_zip_code   apc  \
57520             TN             38401  5491   
57521             TN             38401  5491   
57574             TN             37066  5072   
57575             TN             37066  5073   
57576             TN             37066  5112   
...              ...               ...   ...   
59312             TN             37167  5374   
59313             TN             37167  5375   
59314             TN             37167  5415   
59315             TN             37167  5463   
59316             TN             37167  8011   

                                              apc_desc  capc_services  \
57520                   Level 1 Intraocular Procedures            350   
57521                   Level 1 Intraocular Procedures            350   
57574  Level 2 Excision/ Biopsy/ Incision and Drainage             79   
57575  Level 3 Excision/ Biopsy/ Incision and Drainage             11   
57576               Level 2 Musculoskeletal Procedures             19   
...                                                ...            ...   
59312             Level 4 Urology and Related Services             16   
59313             Level 5 Urology and Related Services             44   
59314                   Level 5 Gynecologic Procedures             12   
59315   Level 3 Neurostimulator and Related Procedures             17   
59316               Comprehensive Observation Services            159   

       average_medicare_allowed_amount   CBSA  
57520                          1660.34  30280  
57521                          1660.34  34980  
57574                          1089.32  34980  
57575                          2010.12  34980  
57576                          1091.34  34980  
...                                ...    ...  
59312                          2378.34  34980  
59313                          3091.00  34980  
59314                          3341.62  34980  
59315                         16612.08  34980  
59316                          1933.77  34980  

[525 rows x 10 columns]

In [31]:
nash_hosp_5302 = nash_hospital[nash_hospital['apc'] == '5302']

USE BELOW TABLE FOR NASHVILLE HOSPITALS

In [32]:
nash_hosp_5302

provider_id                          provider_name   provider_city  \
57584       440003         Sumner Regional Medical Center        Gallatin   
57602       440006         Tristar Skyline Medical Center       Nashville   
57883       440029              Williamson Medical Center        Franklin   
58008       440039   Vanderbilt University Medical Center       Nashville   
58050       440046         Tristar Horizon Medical Center         Dickson   
58051       440046         Tristar Horizon Medical Center         Dickson   
58190       440053       Saint Thomas Rutherford Hospital    Murfreesboro   
58306       440065              Northcrest Medical Center     Springfield   
58399       440073                Maury Regional Hospital        Columbia   
58400       440073                Maury Regional Hospital        Columbia   
58459       440082             Saint Thomas West Hospital       Nashville   
58616       440111       Metro Nashville General Hospital       Nashville   
58783       440133          Saint Thomas Midtown Hospital       Nashville   
58869       440150          Tristar Summit Medical Center       Hermitage   
58986       440161      Tristar Centennial Medical Center       Nashville   
59259       440193             Tennova Healthcare-Lebanon         Lebanon   
59277       440194  Tristar Hendersonville Medical Center  Hendersonville   
59291       440197  Tristar Southern Hills Medical Center       Nashville   
59309       440227      Tristar Stonecrest Medical Center          Smyrna   

      provider_state provider_zip_code   apc                     apc_desc  \
57584             TN             37066  5302  Level 2 Upper GI Procedures   
57602             TN             37207  5302  Level 2 Upper GI Procedures   
57883             TN             37067  5302  Level 2 Upper GI Procedures   
58008             TN             37232  5302  Level 2 Upper GI Procedures   
58050             TN             37055  5302  Level 2 Upper GI Procedures   
58051             TN             37055  5302  Level 2 Upper GI Procedures   
58190             TN             37129  5302  Level 2 Upper GI Procedures   
58306             TN             37172  5302  Level 2 Upper GI Procedures   
58399             TN             38401  5302  Level 2 Upper GI Procedures   
58400             TN             38401  5302  Level 2 Upper GI Procedures   
58459             TN             37205  5302  Level 2 Upper GI Procedures   
58616             TN             37208  5302  Level 2 Upper GI Procedures   
58783             TN             37236  5302  Level 2 Upper GI Procedures   
58869             TN             37076  5302  Level 2 Upper GI Procedures   
58986             TN             37203  5302  Level 2 Upper GI Procedures   
59259             TN             37087  5302  Level 2 Upper GI Procedures   
59277             TN             37075  5302  Level 2 Upper GI Procedures   
59291             TN             37211  5302  Level 2 Upper GI Procedures   
59309             TN             37167  5302  Level 2 Upper GI Procedures   

       capc_services  average_medicare_allowed_amount   CBSA  
57584            114                          1223.45  34980  
57602             15                          1248.62  34980  
57883             18                          1248.62  34980  
58008            623                          1205.62  34980  
58050             13                          1095.57  99999  
58051             13                          1095.57  34980  
58190             55                          1248.62  34980  
58306             29                          1248.62  34980  
58399            254                          1229.64  30280  
58400            254                          1229.64  34980  
58459            207                          1224.59  34980  
58616             12                          1248.62  34980  
58783             98                          1238.47  34980  
58869             21                       

In [33]:
# Filter to just New York Hospitals
# This is ALL New York providers and procedures
ny_hospital = hospital_with_cbsa[hospital_with_cbsa.provider_zip_code.isin(zip_35620)]

In [34]:
# Narrow down to correct APC
ny_hosp_5302 = ny_hospital[ny_hospital['apc'] == '5302']

USE BELOW TABLE FOR NEW YORK HOSPITALS

In [35]:
ny_hosp_5302

provider_id                                   provider_name  \
38521       310001            Hackensack University Medical Center   
38559       310002               Newark Beth Israel Medical Center   
38572       310003                        Palisades Medical Center   
38594       310005                        Hunterdon Medical Center   
38611       310006                      St Mary's General Hospital   
...            ...                                             ...   
43457       330340  University Hospital -  Stony Brook Southampton   
43539       330393                             University Hospital   
43602       330395     St John's Episcopal Hospital At South Shore   
43617       330399                            St Barnabas Hospital   
43632       330401                  St Catherine Of Siena Hospital   

      provider_city provider_state provider_zip_code   apc  \
38521    Hackensack             NJ             07601  5302   
38559        Newark             NJ             07112  5302   
38572  North Bergen             NJ             07047  5302   
38594    Flemington             NJ             08822  5302   
38611       Passaic             NJ             07055  5302   
...             ...            ...               ...   ...   
43457   Southampton             NY             11968  5302   
43539   Stony Brook             NY             11794  5302   
43602  Far Rockaway             NY             11691  5302   
43617         Bronx             NY             10457  5302   
43632     Smithtown             NY             11787  5302   

                          apc_desc  capc_services  \
38521  Level 2 Upper GI Procedures            197   
38559  Level 2 Upper GI Procedures             20   
38572  Level 2 Upper GI Procedures             22   
38594  Level 2 Upper GI Procedures             53   
38611  Level 2 Upper GI Procedures             39   
...                            ...            ...   
43457  Level 2 Upper GI Procedures             17   
43539  Level 2 Upper GI Procedures            494   
43602  Level 2 Upper GI Procedures             17   
43617  Level 2 Upper GI Procedures             25   
43632  Level 2 Upper GI Procedures             22   

       average_medicare_allowed_amount   CBSA  
38521                          1538.63  35620  
38559                          1528.38  35620  
38572                          1544.85  35620  
38594                          1398.08  35620  
38611                          1544.85  35620  
...                                ...    ...  
43457                          1589.69  35620  
43539                          1571.75  35620  
43602                          1589.69  35620  
43617                          1589.81  35620  
43632                          1589.87  35620  

[90 rows x 10 columns]

Option 1 Stretch 1
Extend to other HCPCS/APCs
    Best place to start is to find an APC that is well-populated in the Hospital file
    Next find a well-populated HCPCS from the APC in the Physician/Other Supplier File
    How many patients do providers in zip A see compared to zip B?


In [36]:
# Find well populated APC nationwide
# Use 5114    Level 4 musculoskeletal procedures aka procedures for when you get older. Makes sense
hospital_with_cbsa['apc'].value_counts()

8011    3568
5072    3155
5113    3076
5361    3006
5114    2959
5341    2705
5302    2674
5375    2579
5112    2520
5373    2423
5374    2338
5431    2287
5191    2135
5073    2135
5491    2054
5193    1974
5091    1740
5223    1724
5092    1654
5414    1609
5192    1552
5115    1437
5154    1389
5362    1320
5153    1304
5194    1229
5222    1150
5232    1133
5415    1001
5165     952
5213     903
5313     842
5492     823
5303     800
5155     735
5164     653
5503     618
5464     604
5231     514
5462     489
5331     486
5463     446
5376     359
5627     278
5416     270
5377     258
5212     253
5224     253
5504     164
5471     149
5166     117
5116      80
5094      51
5432      50
5093      41
5200      40
5211       9
5493       3
Name: apc, dtype: int64

In [45]:
# crosswalk[ro]

In [38]:
hospital_5114 = hospital_with_cbsa[hospital_with_cbsa['apc'] == '5114']

USE TABLE BELOW FOR NATIONWIDE HOSPITALS UNDER APC 5114

In [39]:
# nationwide 5114 hospitals
hospital_5114

provider_id                                     provider_name  \
6            10001                  Southeast Alabama Medical Center   
66           10005                     Marshall Medical Center South   
67           10005                     Marshall Medical Center South   
68           10005                     Marshall Medical Center South   
69           10005                     Marshall Medical Center South   
...            ...                                               ...   
71031       670112                      Cumberland Surgical Hospital   
71040       670116                                Wise Health System   
71051       670119          Providence Hospital Of North Houston Llc   
71055       670120  The Hospitals Of Providence Transmountain Campus   
71059       670122          Houston Methodist The Woodlands Hospital   

       provider_city provider_state provider_zip_code   apc  \
6             Dothan             AL             36301  5114   
66              Boaz             AL             35957  5114   
67              Boaz             AL             35957  5114   
68              Boaz             AL             35957  5114   
69              Boaz             AL             35957  5114   
...              ...            ...               ...   ...   
71031    San Antonio             TX             78249  5114   
71040     Fort Worth             TX             76177  5114   
71051        Houston             TX             77090  5114   
71055        El Paso             TX             79911  5114   
71059  The Woodlands             TX             77385  5114   

                                 apc_desc  capc_services  \
6      Level 4 Musculoskeletal Procedures            175   
66     Level 4 Musculoskeletal Procedures            126   
67     Level 4 Musculoskeletal Procedures            126   
68     Level 4 Musculoskeletal Procedures            126   
69     Level 4 Musculoskeletal Procedures            126   
...                                   ...            ...   
71031  Level 4 Musculoskeletal Procedures             53   
71040  Level 4 Musculoskeletal Procedures            103   
71051  Level 4 Musculoskeletal Procedures             23   
71055  Level 4 Musculoskeletal Procedures             13   
71059  Level 4 Musculoskeletal Procedures             35   

       average_medicare_allowed_amount   CBSA  
6                              4399.54  20020  
66                             4433.83  22840  
67                             4433.83  13820  
68                             4433.83  23460  
69                             4433.83  10700  
...                                ...    ...  
71031                          4711.67  41700  
71040                          4878.58  19100  
71051                          5031.05  26420  
71055                          4497.41  21340  
71059                          4916.52  26420  

[2959 rows x 10 columns]

In [ ]:
# Get Nashville hospitals for code 5114


In [46]:
# Get all physicians under 5114 apc, code 63047 nationwide

In [40]:
# Get associated hcpcs codes from apc 
crosswalk_5114 = crosswalk[crosswalk['apc'] == 5114]
crosswalk_5114.drop(['national_unadjusted_copayment', 'si', 'relative_weight', 'minimum_unadjusted_copayment', 'note:_actual_copayments_would_be_lower_due_to_the_cap_on_copayments_at_the_inpatient_deductible_of_$1,408.00', '*_indicates_a_change', 'unnamed:_10'], axis = 1)

hcpcs_code              short_descriptor     apc payment_rate
399        11970       Replace tissue expander  5114.0    $5,981.95
710        20251              Open bone biopsy  5114.0    $5,981.95
741        20690    Apply bone fixation device  5114.0    $5,981.95
743        20693   Adjust bone fixation device  5114.0    $5,981.95
761        20900     Removal of bone for graft  5114.0    $5,981.95
...          ...                           ...     ...          ...
9703       0275T         Perq lamot/lam lumbar  5114.0    $5,981.95
9722       0335T      Insj sinus tarsi implant  5114.0    $5,981.95
9868       0511T  Rmvl&rinsj sinus tarsi implt  5114.0    $5,981.95
12881      G0276  Pild/placebo control clin tr  5114.0    $5,981.95
12937      G0413  Pelvic ring fracture uni/bil  5114.0    $5,981.95

[332 rows x 4 columns]

In [41]:
# Nationwide providers under apc 5114
physician_5114_apc = physician_with_cbsa[physician_with_cbsa.hcpcs_code.isin(crosswalk_5114['hcpcs_code'])]

In [42]:
# Well populated hcpcs code from 5114 apc is 63047
physician_5114_apc['hcpcs_code'].value_counts()

63047    5399
29827    3963
63030    1058
29828     714
23430     684
         ... 
25825       1
28585       1
27696       1
27065       1
26842       1
Name: hcpcs_code, Length: 127, dtype: int64

Top 5 providers are
Orthopedic Surgery                      6811
Physician Assistant                     3383
Neurosurgery                            3000
Ambulatory Surgical Center              1557
Nurse Practitioner                       500

In [43]:
# Create dataframe containing only 63047 hcpcs codes
# Nationwide
physician_63047 = physician_5114_apc[(physician_5114_apc['hcpcs_code'] == '63047')]

USE BELOW TABLE FOR NATIONWIDE PHYSICIANS UNDER CODE 63047 
<b>
This will be comparing doctors themselves and thus not the overall cost of a procedure, just the doctors portion (most likely)

In [44]:
physician_63047

npi         nppes_provider_last_org_name  \
3877      1003018748                               THOMAS   
5533      1003027392                                 CURT   
9637      1003050071                                ROHDE   
9747      1003050493                            AUSCHWITZ   
10394     1003055666                               MILLER   
...              ...                                  ...   
10977918  1992961361                                YOCUM   
10979900  1992968606                              FARHADI   
10981823  1992983662                             RENTFROW   
10982091  1992986434                                MARSH   
10983875  1992999775  SPINE SURGERY CENTER OF EUGENE, LLC   

         nppes_provider_first_name nppes_credentials nppes_entity_code  \
3877                          BRAD                MD                 I   
5533                      BRADFORD                MD                 I   
9637                       BREANNE              PA-C                 I   
9747                         TYLER               NaN                 I   
10394                       JUSTIN                PA                 I   
...                            ...               ...               ...   
10977918                     TONIA              PA-C                 I   
10979900                    HOOMAN                MD                 I   
10981823                     COREY            P.A.-C                 I   
10982091                    ROBERT       M.D., PH.D.                 I   
10983875                       NaN               NaN                 O   

         nppes_provider_zip nppes_provider_state               provider_type  \
3877                  72205                   AR                Neurosurgery   
5533                  45069                   OH                Neurosurgery   
9637                  98664                   WA         Physician Assistant   
9747                  74104                   OK                Neurosurgery   
10394                 49525                   MI         Physician Assistant   
...                     ...                  ...                         ...   
10977918              23601                   VA         Physician Assistant   
10979900              43210                   OH                Neurosurgery   
10981823              63122                   MO         Physician Assistant   
10982091              25701                   WV                Neurosurgery   
10983875              97401                   OR  Ambulatory Surgical Center   

         place_of_service hcpcs_code  bene_day_srvc_cnt  \
3877                    F      63047                 67   
5533                    F      63047                 42   
9637                    F      63047                 25   
9747                    F      63047                 21   
10394                   F      63047                 13   
...                   ...        ...                ...   
10977918                F      63047                 81   
10979900                F      63047                 11   
10981823                F      63047                 66   
10982091                F      63047                 15   
10983875                F      63047                 22   

          average_medicare_allowed_amt   CBSA  
3877                        751.756269  30780  
5533                        889.988095  17140  
9637                        144.441200  38900  
9747                        738.330000  46140  
10394                       110.696923  24340  
...                                ...    ...  
10977918                     80.035926  47260  
10979900                    545.405455  18140  
10981823                    106.054545  41180  
10982091                   1057.933333  26580  
10983875                   2803.287273  21660  

[5399 rows x 13 columns]

Option 1 Stretch 2
Compare Doctor Utilization for a procedure
    Filters for Physician/Other Supplier
    Entity Type = I
    Place of Service = O
    HCPCS = 99213 (or any office visit – 99211-99215 / 99201-99205)
    How many different patients does each specialty typically see in a year? How does that vary by CBSA?


In [ ]:
# Narrow down physicians to just office visits 
# HCPCS = 99213 (or any office visit – 99211-99215 / 99201-99205)

In [47]:
office_visit = ['99213', '99211', '99212','99213','99214','99215', '99201','99202','99203','99204','99205']

In [53]:
phys_office = physician_with_cbsa[(physician_with_cbsa['nppes_entity_code'] == 'I') & (physician_with_cbsa['place_of_service'] == 'O')]

In [54]:
phys_office

npi nppes_provider_last_org_name nppes_provider_first_name  \
37        1003000142                       KHALIL                    RASHID   
38        1003000142                       KHALIL                    RASHID   
39        1003000142                       KHALIL                    RASHID   
41        1003000142                       KHALIL                    RASHID   
42        1003000142                       KHALIL                    RASHID   
...              ...                          ...                       ...   
10983883  1992999825                    DESCHENES                  GEOFFREY   
10983885  1992999825                    DESCHENES                  GEOFFREY   
10983887  1992999825                    DESCHENES                  GEOFFREY   
10983889  1992999825                    DESCHENES                  GEOFFREY   
10983891  1992999825                    DESCHENES                  GEOFFREY   

         nppes_credentials nppes_entity_code nppes_provider_zip  \
37                    M.D.                 I              43623   
38                    M.D.                 I              43623   
39                    M.D.                 I              43623   
41                    M.D.                 I              43623   
42                    M.D.                 I              43623   
...                    ...               ...                ...   
10983883              M.D.                 I              98101   
10983885              M.D.                 I              98101   
10983887              M.D.                 I              98101   
10983889              M.D.                 I              98101   
10983891              M.D.                 I              98101   

         nppes_provider_state   provider_type place_of_service hcpcs_code  \
37                         OH  Anesthesiology                O      99204   
38                         OH  Anesthesiology                O      99205   
39                         OH  Anesthesiology                O      99213   
41                         OH  Anesthesiology                O      99214   
42                         OH  Anesthesiology                O      99215   
...                       ...             ...              ...        ...   
10983883                   WA  Otolaryngology                O      31575   
10983885                   WA  Otolaryngology                O      69210   
10983887                   WA  Otolaryngology                O      99203   
10983889                   WA  Otolaryngology                O      99204   
10983891                   WA  Otolaryngology                O      99214   

          bene_day_srvc_cnt  average_medicare_allowed_amt   CBSA  
37                       73                    160.330000  45780  
38                       36                    202.250000  45780  
39                      129                     70.930000  45780  
41                      330                    104.530000  45780  
42                       49                    141.060000  45780  
...                     ...                           ...    ...  
10983883                 63                    127.160000  42660  
10983885                104                     52.807212  42660  
10983887                 88                    117.260000  42660  
10983889                105                    176.900000  42660  
10983891                248                    116.860000  42660  

[6461884 rows x 13 columns]

In [56]:
phys_office = phys_office[phys_office['hcpcs_code'].isin(office_visit)]

In [59]:
phys_office_group = phys_office.groupby(['provider_type', 'CBSA']).sum().reset_index()

USE BELOW TABLE FOR OFFICE VISITS BY PROVIDER TYPE BY CBSA

In [61]:
phys_office_group

provider_type   CBSA           npi  bene_day_srvc_cnt  \
0      Addiction Medicine  10420    1285669481                 58   
1      Addiction Medicine  10580    5516757423                844   
2      Addiction Medicine  10740    2612178626                188   
3      Addiction Medicine  11220    2854233032                252   
4      Addiction Medicine  11460    5008771056                388   
...                   ...    ...           ...                ...   
26982    Vascular Surgery  49620   38687740813               2430   
26983    Vascular Surgery  49660   50337375139               2697   
26984    Vascular Surgery  49700    6516740912                713   
26985    Vascular Surgery  49780    9269457888                764   
26986    Vascular Surgery  99999  247968669821              16689   

       average_medicare_allowed_amt  
0                         69.510000  
1                        273.590000  
2                        129.660000  
3                        102.360000  
4                        472.670000  
...                             ...  
26982                   2402.933333  
26983                   3410.577176  
26984                    511.460000  
26985                    735.770000  
26986                  16995.357533  

[26987 rows x 5 columns]

List all dataframes for CSVs

In [65]:
# dt.to_csv('C:/Users/abc/Desktop/file_name.csv')
# "C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV"
nash_prov_43249.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\nash_prov_43249.csv", encoding='utf-8', index=False)
ny_prov_43249.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\ny_prov_43249.csv", encoding='utf-8', index=False)
nash_hosp_5302.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\nash_hosp_5302.csv", encoding='utf-8', index=False)
ny_hosp_5302.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\ny_hosp_5302.csv", encoding='utf-8', index=False)
hospital_5114.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\hospital_5114.csv", encoding='utf-8', index=False)
physician_63047.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\physician_63047.csv", encoding='utf-8', index=False)
phys_office_group.to_csv(r"C:\Users\toshi\Documents\NSS Documents\Projects\Python\healthcare-bluebook-red-team\Option_1_CSV\phys_office_group.csv", encoding='utf-8', index=False)